### ISSUE TITLE
Crash upon firing a wand with chain bolt and not hitting anything

### ISSUE THREAD

**Issue by MasonGulu** [OHakimen/Wandrous#2]
I gave myself a wand, and placed 'chain bolt' inside it as the only spell. I then fired the wand, after a split second of particles the game crashes. That world now cannot be loaded because of the remaining spell entity.

[Initial crash](https://github.com/user-attachments/files/17181141/crash-2024-09-29_16.22.46-server.txt)

[Second load](https://github.com/user-attachments/files/17181143/crash-2024-09-29_20.20.52-server.txt)

**Comment by OHakimen** [comment]
found the problem
it was trying to play the finish spell sound to the player, but the context existance wasnt checked, fixed it now
